### ISSUE TITLE
Doesn't work with Personal & Business Dropbox folder

### ISSUE THREAD

**Issue by jvdmeij** [itspriddle/shotty#14]
I loved dropbox-screenshots-plist, but after installing a new mac I found it is deprecated. So I tried shotty.

After installing it, it seems like it is not compatible with a Dropbox folder name that is not 'Dropbox. If you have an business account, your personal folder is no longer just "Dropbox" but "Dropbox (Personal)".

A symlink and changing the screenshot folder in the config, makes it work. 

It might be an idea to either extend the install guide, or building support for other folder names.

**Comment by itspriddle** [comment]
@jvdmeij sorry I missed this. I will see about adding a configuration option to specify the root Dropbox folder.

**Comment by jvdmeij** [comment]
@itspriddle No worries, I fixed it while working with it. Was a heads up for you to implement in a future update :)

**Comment by itspriddle** [comment]
#16 should fix this. Would you mind giving it a try when you have a few minutes and let me know if it works out? Thanks!

**Comment by jvdmeij** [comment]
Yes, that seemed to work like a charm! 👍

**Comment by itspriddle** [comment]
Thanks! I will get a new release pushed up tonight.

**Comment by itspriddle** [comment]
https://github.com/itspriddle/shotty/releases/tag/v0.1.0

Thanks again for the bug report!
